name: Check the links in the Outlet

on: push

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Markdown Link Checker
        uses: gaurav-nelson/github-action-markdown-link-check@1.0.14
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          file-path: './README.md'
          config-file: 'mlc_config.json'
